services:
  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache


    networks:
      - test_poo

  nginx:
    image: nginx:alpine
    container_name: nginx_test_poo
    restart: unless-stopped
    ports:
      - "8181:80"

    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx

    depends_on:
      - php-fpm

    networks:
      - test_poo

networks:
  test_poo:

volumes:
  db_data: